### ISSUE TITLE
Early acces to releases in Github

### ISSUE THREAD

**Issue by Nikolas-Lehto** [grondag/clear-skies#18]
In my opinion adding already ready releases to the Github releases page before Modrinth and CurseForge accepts them, would be a good idea. I have been waiting for 1.20.x version of Clear Skies pretty long time now and because in [this](https://github.com/grondag/clear-skies/issues/17#issuecomment-1635025856) reply you said it is only waiting for approval from Modrinth and CurseForge, i hope you will consider this idea.

P.S. Sorry for my perhaps bad English and thanks for developing such a great mod.

EDIT: Corrected some typos

**Comment by pleepish** [comment]
i agree. i've been waiting for 1.20.x forever. i love this mod.

**Comment by Timolino456** [comment]
The reply you linked is not by the author of the mod. It has not been uploaded to Curseforge or Modrinth, otherwise it would've been approved already. The author said in their Discord in july that they just don't have the motivation for mod updates atm. They might return and update it at some point. Or someone else does it and submits a pull request, like someone did for 1.19.4.

**Comment by Nikolas-Lehto** [comment]
Oh, ok :D Looks like i'm the dumb one here. I'l close this issue now.
